<?php
/**
 * Module file for Kala Migrate.
 */

// Load function files for processing.
require_once dirname(__FILE__) . '/includes/content_types.inc';
require_once dirname(__FILE__) . '/includes/features.inc';
require_once dirname(__FILE__) . '/includes/fields.inc';
require_once dirname(__FILE__) . '/includes/fpp.inc';
require_once dirname(__FILE__) . '/includes/image_styles.inc';
require_once dirname(__FILE__) . '/includes/menus.inc';
require_once dirname(__FILE__) . '/includes/pm_pages.inc';
require_once dirname(__FILE__) . '/includes/redirect.inc';
require_once dirname(__FILE__) . '/includes/views.inc';
require_once dirname(__FILE__) . '/includes/vocab.inc';
require_once dirname(__FILE__) . '/includes/user_roles.inc';
require_once dirname(__FILE__) . '/includes/zip.inc';

/**
 * Implements hook_menu().
 */
function kala_migrate_menu() {
  $items = array();

  $items['admin/config/development/kala_migrate'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('Kala Migrate Settings'),
    'description' => t('Setting to Automate Migration to Drupal 8.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_kala_migrate_settings_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function kala_migrate_form_alter(&$form, &$form_state, $form_id) {
  // We have to change the submit button text in the HFA.
  if ($form_id == '_kala_migrate_settings_form') {
    $form['actions']['submit']['#value'] = 'Download ZIP';
  }
}

/**
 * hook_menu Page Callback.
 */
function _kala_migrate_settings_form() {

  $form['ct'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content Based Items'),
  );

  $form['ct']['content_types'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all Content Types and their data (includes some field data)'),
    '#default_value' => 1,
  );

  $form['ct']['fields'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get full Fields data (more detailed)'),
    '#default_value' => 1,
  );

  $form['tx'] = array(
    '#type' => 'fieldset',
    '#title' => t('Taxonomy Based Items'),
  );

  $form['tx']['vocab'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all of the Taxonomy Vocabulary Settings?'),
    '#default_value' => 1,
  );

  $form['ps'] = array(
    '#type' => 'fieldset',
    '#title' => t('Panels Based Items'),
  );

  if (module_exists('page_manager')) {
    $form['ps']['pm_pages'] = array(
      '#type' => 'checkbox',
      '#title' => t('Get all of the Page Manager Pages and their Settings?'),
      '#default_value' => 1,
    );
  }

  if (module_exists('fieldable_panels_panes')) {
    $form['ps']['fpp'] = array(
      '#type' => 'checkbox',
      '#title' => t('Get all of Fieldable Panels Panes?'),
      '#default_value' => 1,
    );
  }

  $form['is'] = array(
    '#type' => 'fieldset',
    '#title' => t('Image Based Items'),
  );

  $form['is']['image_styles'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all Image Styles and Settings?'),
    '#default_value' => 1,
  );

  $form['vs'] = array(
    '#type' => 'fieldset',
    '#title' => t('Views Based Items'),
  );

  $form['vs']['views'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all Views and their Settings?'),
    '#default_value' => 1,
  );

  $form['am'] = array(
    '#type' => 'fieldset',
    '#title' => t('Admin Based Items'),
  );

  if (module_exists('features')) {
    $form['am']['feat'] = array(
      '#type' => 'checkbox',
      '#title' => t('Get all of the Features and their Settings?'),
      '#default_value' => 1,
    );
  }

  $form['am']['menus'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all of the Menu Settings?'),
    '#default_value' => 1,
  );

  $form['am']['roles'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all of the User Roles?'),
    '#default_value' => 1,
  );

  if (module_exists('redirect')) {
    $form['am']['redirect'] = array(
      '#type' => 'checkbox',
      '#title' => t('Get all of the Redirects?'),
      '#default_value' => 1,
    );
  }

  $form['#submit'][] = '_kala_migrate_settings_form_submit';

  return system_settings_form($form);
}

/**
 * Submit handler for form.
 */
function _kala_migrate_settings_form_submit($form, &$form_state) {
  $files = array();
  $values = $form_state['values'];

  // The Content Type & Fields Settings.
  if ($values['content_types']) {
    $files[] = _kala_migrate_content_types('content-types.csv');
  }

  // The Full Fields Settings.
  if ($values['fields']) {
    $files[] = _kala_migrate_fields('fields.csv');
  }

  // The Taxonomy Vocabulary Settings.
  if ($values['vocab']) {
    $files[] = _kala_migrate_vocab('vocab.csv');
  }

  // The Page Manager Pages.
  if (module_exists('page_manager')) {
    if ($values['pm_pages']) {
      $files[] = _kala_migrate_pm_pages('page-manager-pages.csv');
    }
  }

  // The FPP Items.
  if (module_exists('fieldable_panels_panes')) {
    if ($values['fpp']) {
      $files[] = _kala_migrate_fpp('fieldable-panels-panes.csv');
    }
  }

  // The Image Styles & Settings.
  if ($values['image_styles']) {
    $files[] = _kala_migrate_image_styles('image-styles.csv');
  }

  // The Views Settings.
  if ($values['views']) {
    $files[] = _kala_migrate_views('views.csv');
  }

  if (module_exists('features')) {
    if ($values['feat']) {
      $files[] = _kala_migrate_features('features.csv');
    }
  }

  // The Menus Settings.
  if ($values['menus']) {
    $files[] = _kala_migrate_menus('menus.csv');
  }

  // The Menus Settings.
  if ($values['roles']) {
    $files[] = _kala_migrate_user_roles('user-roles.csv');
  }

  // The Redirect Settings.
  if (module_exists('redirect')) {
    if ($values['redirect']) {
      $files[] = _kala_migrate_redirects('redirects.csv');
    }
  }

  // If there are files, lets do this!
  if (count($files) > 0) {
    _kala_migrate_create_zip($files);
  }

  // Get to the chopper!
  exit;
}
