<?php
/**
 * Module file for Kala Migrate.
 */

// Load function files for processing.
require_once dirname(__FILE__) . '/includes/content_types.inc';
require_once dirname(__FILE__) . '/includes/fields.inc';
require_once dirname(__FILE__) . '/includes/image_styles.inc';
require_once dirname(__FILE__) . '/includes/zip.inc';

/**
 * Implements hook_menu().
 */
function kala_migrate_menu() {
  $items = array();

  $items['admin/config/development/kala_migrate'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('Kala Migrate Settings'),
    'description' => t('Setting to Automate Migration to Drupal 8.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_kala_migrate_settings_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * hook_menu Page Callback.
 */
function _kala_migrate_settings_form() {

  $form['content_types'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all Content Types and the their data (includes some field data)'),
    '#default_value' => 1,
  );

  $form['fields'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get full Fields data (more detailed)'),
    '#default_value' => 1,
  );

  $form['image_styles'] = array(
    '#type' => 'checkbox',
    '#title' => t('Get all Image Styles and Settings?'),
    '#default_value' => 1,
  );


  $form['#submit'][] = '_kala_migrate_settings_form_submit';

  return system_settings_form($form);
}

/**
 * Submit handler for form.
 */
function _kala_migrate_settings_form_submit($form, &$form_state) {
  $files = array();

  // The Content Type & Fields Settings.
  if ($form_state['values']['content_types']) {
    $files[] = _kala_migrate_content_types('content-types.csv');
  }

  // The Full Fields Settings.
  if ($form_state['values']['fields']) {
    $files[] = _kala_migrate_fields('fields.csv');
  }

  // The Image Styles & Settings.
  if ($form_state['values']['image_styles']) {
    $files[] = _kala_migrate_image_styles('image-styles.csv');
  }

  // If there are files, lets do this!
  if (count($files) > 0) {
    _kala_migrate_create_zip($files);
  }

  // Get to the chopper!
  exit;
}
